CapaPresentacionAdmin/Controllers/MantenimientoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaNegocio;
using Newtonsoft.Json;

namespace CapaPresentacionAdmin.Controllers
{
    [Authorize]
    public class MantenimientoController : Controller
    {
        // GET: Mantenimiento
        public ActionResult Categoria()
        {
            return View();
        }

        public ActionResult Marca()
        {
            return View();
        }

        public ActionResult Producto()
        {
            return View();
        }

        #region Categoria

        [HttpGet]
        public JsonResult ListarCategorias()
        {
            List<Categoria> oLista = new List<Categoria>();
            oLista = new CN_Categoria().Listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarCategoria(Categoria categoria)
        {
            object resultado;
            string mensaje = string.Empty;

            if (categoria.IdCategoria == 0)
            {
                resultado = new CN_Categoria().Registrar(categoria, out mensaje);
            }
            else
            {
                resultado = new CN_Categoria().Editar(categoria, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarCategoria(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Categoria().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Marca

        [HttpGet]
        public JsonResult ListarMarcas()
        {
            List<Marca> oLista = new List<Marca>();
            oLista = new CN_Marca().Listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarMarca(Marca marca)
        {
            object resultado;
            string mensaje = string.Empty;

            if (marca.IdMarca == 0)
            {
                resultado = new CN_Marca().Registrar(marca, out mensaje);
            }
            else
            {
                resultado = new CN_Marca().Editar(marca, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarMarca(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Marca().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Producto

        [HttpGet]
        public JsonResult ListarProducto()
        {
            List<Producto> oLista = new List<Producto>();
            oLista = new CN_Producto().Listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarProducto(string producto, HttpPostedFileBase archivoImagen)
        {
            string mensaje = string.Empty;
            bool operacionExitosa = true;
            bool guardarImagenExitosamente = true;

            Producto oProducto = new Producto();
            oProducto = JsonConvert.DeserializeObject<Producto>(producto);

            decimal precio;

            if(decimal.TryParse(oProducto.PrecioTexto,System.Globalization.NumberStyles.AllowDecimalPoint,new CultureInfo("es-AR"),out precio))
            {
                oProducto.Precio = precio;
            }
            else
            {
                return Json(new { operacionExitosa = false, mensaje = "El formato del precio no es correcto" },JsonRequestBehavior.AllowGet);
            }

            if (oProducto.IdProducto == 0)
            {
                int idGenerado = new CN_Producto().Registrar(oProducto, out mensaje);

                if (idGenerado != 0)
                    oProducto.IdProducto = idGenerado;
                else
                    operacionExitosa = false;
            }
            else
            {
                operacionExitosa = new CN_Producto().Editar(oProducto, out mensaje);
            }

            if(operacionExitosa)
            {
                if(archivoImagen != null)
                {
                    string pathImagenes = ConfigurationManager.AppSettings["ServidorFotos"];
                    string extension = Path.GetExtension(archivoImagen.FileName);
                    string nombreImagen = string.Concat(oProducto.IdProducto.ToString(),extension);

                    try
                    {
                        archivoImagen.SaveAs(Path.Combine(pathImagenes, nombreImagen));
                    }
                    catch(Exception e)
                    {
                        string msg = e.Message;
                        guardarImagenExitosamente = false;
                    }

                    if(guardarImagenExitosamente)
                    {
                        oProducto.RutaImagen = pathImagenes;
                        oProducto.NombreImagen = nombreImagen;
                        bool resp = new CN_Producto().GuardarDatosImagen(oProducto, out mensaje);
                    }
                    else
                    {
                        mensaje = "No se pudo guardar la imagen del producto";
                    }
                }
            }

            return Json(new { operacionExitosa = operacionExitosa,idGenerado = oProducto.IdProducto ,mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ImagenProducto(int id)
        {
            bool conversion;
            Producto oProducto = new CN_Producto().Listar().Where(p => p.IdProducto == id).FirstOrDefault();

            string textoBase64 = CN_Recursos.ConvertirImagenBase64(Path.Combine(oProducto.RutaImagen, oProducto.NombreImagen),out conversion);

            return Json(new
            {
                conversion = conversion,
                textoBase64 = textoBase64,
                extension = Path.GetExtension(oProducto.NombreImagen)
            },
                JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarProducto(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Producto().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

CapaPresentacionAdmin/Views/Mantenimiento/Categoria.cshtml
@{
    ViewBag.Title = "Categoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Categorias</li>
</ol>


<div class="card">
    <div class="card-header">
        <i class="fas fa-table"></i> Lista de Categorias
    </div>

    <div class="card-body col-lg-12">
        <div class="row">
            <div>
                <button type="button" class="btn btn-success" onclick="abrir_Modal()">Crear Categoria</button>
            </div>
        </div>

        <hr />

        <table id="Tabla" class="display cell-border" style="width: 100%">

            <thead>
                <tr>
                    <th>Descripcion</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Categoria</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <div class="modal-body">

                <input id="txtId" type="hidden" value="0" />

                <div class="row g-1">

                    <div class="col-sm-6">
                        <label for="txtDescripcion" class="form-label">Descripcion</label>
                        <input type="text" class="form-control" id="txtDescripcion" autocomplete="off">
                    </div>

                    @*Mensaje de alerta*@
                    <div class="col-sm-6">
                        <label for="cboActivo" class="form-label">Activo</label>
                        <select class="form-select col-sm-6" id="cboActivo">
                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>



                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>



@section scripts{
    <script>

        var tablaData;
        var filaSeleccionada;



        tablaData = $("#Tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarCategorias", "Mantenimiento")',
                type: "GET",
                dataType: "json"
            },
            "columns": [
                { "data": "Descripcion" },
                { "data": "Activo", "render": function (valor) {
                        if (valor)
                            return '<span class="badge bg-success">Si</span>'
                        else
                            return '<span class="badge bg-danger">No</span>'
                    }
                },
                {
                    "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                    orderable: false,
                    searchable: false,
                    "width":"90px"
                }
            ],
            "language": {
                "url":"https://cdn.datatables.net/plug-ins/1.13.4/i18n/es-ES.json"
            }

        });

        function abrir_Modal(json=null)
        {
            $("#txtId").val(0);
            $("#txtDescripcion").val("");
            $("#cboActivo").val(1);
            $("#mensajeError").hide();

            if (json != null)
            {
                $("#txtId").val(json.IdCategoria);
                $("#txtDescripcion").val(json.Descripcion);
                $("#cboActivo").val(json.Activo == true ? 1 : 0);
            }

            $("#FormModal").modal("show");
        }

        function Guardar()
        {
            var Categoria =
            {
                IdCategoria: $("#txtId").val(),
                Descripcion: $("#txtDescripcion").val(),
                Activo: $("#cboActivo").val() == 1 ? true : false                
            }

            jQuery.ajax({
                url: '@Url.Action("GuardarCategoria", "Mantenimiento")',
                type: "POST",
                data: JSON.stringify({ categoria: Categoria }),
                dataType: 'json',
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $(".modal-body").LoadingOverlay("hide");
                    //CATEGORIA NUEVA
                    
                    if (Categoria.IdCategoria == 0) {
                        if (data.resultado != 0) {
                            Categoria.IdCategoria = data.resultado;
                            tablaData.row.add(Categoria).draw(false);
                            $("#FormModal").modal("hide");
                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                    //EDITAR CATEGORIA
                    else {
                        if (data.resultado) {
                            tablaData.row(filaSeleccionada).data(Categoria).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }

                    }
                },

                error: function (error) {
                    $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },

                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    });
                },
            });


        }

        $("#Tabla tbody").on("click", '.btn-editar', function () {
            filaSeleccionada = $(this).closest("tr");

            var data = tablaData.row(filaSeleccionada).data();

            abrir_Modal(data)

        })

        $("#Tabla tbody").on("click", '.btn-eliminar', function () {

            var categoriaSeleccionada = $(this).closest("tr");

            var data = tablaData.row(categoriaSeleccionada).data();

            swal({
                title: "Confirme",
                text: "¿Desea eliminar la categoria?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
                function () {
                    jQuery.ajax({
                        url: '@Url.Action("EliminarCategoria", "Mantenimiento")',
                        type: "POST",
                        data: JSON.stringify({ id: data.IdCategoria }),
                        dataType: "json",

                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            if (data.resultado == true) {
                                tablaData.row(categoriaSeleccionada).remove().draw();
                            }
                            else {
                                swal("No se pudo eliminar", data.mensaje, "error");
                            }
                        }
                    })
                }
            );

         });



    </script>


}

CapaPresentacionAdmin/Views/Mantenimiento/Marca.cshtml
@{
    ViewBag.Title = "Marca";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Marcas</li>
</ol>


<div class="card">
    <div class="card-header">
        <i class="fas fa-bookmark"></i> Lista de Marcas
    </div>

    <div class="card-body col-lg-12">
        <div class="row">
            <div>
                <button type="button" class="btn btn-success" onclick="abrir_Modal()">Crear Marca</button>
            </div>
        </div>

        <hr />

        <table id="Tabla" class="display cell-border" style="width: 100%">

            <thead>
                <tr>
                    <th>Descripcion</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Marca</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <div class="modal-body">

                <input id="txtId" type="hidden" value="0" />

                <div class="row g-1">

                    <div class="col-sm-6">
                        <label for="txtDescripcion" class="form-label">Descripcion</label>
                        <input type="text" class="form-control" id="txtDescripcion" autocomplete="off">
                    </div>

                    @*Mensaje de alerta*@
                    <div class="col-sm-6">
                        <label for="cboActivo" class="form-label">Activo</label>
                        <select class="form-select col-sm-6" id="cboActivo">
                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>



                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>



@section scripts{
    <script>

        var tablaData;
        var filaSeleccionada;



        tablaData = $("#Tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarMarcas", "Mantenimiento")',
                type: "GET",
                dataType: "json"
            },
            "columns": [
                { "data": "Descripcion" },
                { "data": "Activo", "render": function (valor) {
                        if (valor)
                            return '<span class="badge bg-success">Si</span>'
                        else
                            return '<span class="badge bg-danger">No</span>'
                    }
                },
                {
                    "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                    orderable: false,
                    searchable: false,
                    "width":"90px"
                }
            ],
            "language": {
                "url":"https://cdn.datatables.net/plug-ins/1.13.4/i18n/es-ES.json"
            }

        });

        function abrir_Modal(json=null)
        {
            $("#txtId").val(0);
            $("#txtDescripcion").val("");
            $("#cboActivo").val(1);
            $("#mensajeError").hide();

            if (json != null)
            {
                $("#txtId").val(json.IdMarca);
                $("#txtDescripcion").val(json.Descripcion);
                $("#cboActivo").val(json.Activo == true ? 1 : 0);
            }

            $("#FormModal").modal("show");
        }

        function Guardar()
        {
            var Marca =
            {
                IdMarca: $("#txtId").val(),
                Descripcion: $("#txtDescripcion").val(),
                Activo: $("#cboActivo").val() == 1 ? true : false
            }

            jQuery.ajax({
                url: '@Url.Action("GuardarMarca", "Mantenimiento")',
                type: "POST",
                data: JSON.stringify({ marca: Marca }),
                dataType: 'json',
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $(".modal-body").LoadingOverlay("hide");
                    //MARCA NUEVA

                    if (Marca.IdMarca == 0) {
                        if (data.resultado != 0) {
                            Marca.IdMarca = data.resultado;
                            tablaData.row.add(Marca).draw(false);
                            $("#FormModal").modal("hide");
                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                    //EDITAR MARCA
                    else {
                        if (data.resultado) {
                            tablaData.row(filaSeleccionada).data(Marca).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }

                    }
                },

                error: function (error) {
                    $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },

                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    });
                },
            });


        }

        $("#Tabla tbody").on("click", '.btn-editar', function () {
            filaSeleccionada = $(this).closest("tr");

            var data = tablaData.row(filaSeleccionada).data();

            abrir_Modal(data)

        })

        $("#Tabla tbody").on("click", '.btn-eliminar', function () {

            var marcaSeleccionada = $(this).closest("tr");

            var data = tablaData.row(marcaSeleccionada).data();

            swal({
                title: "Confirme",
                text: "¿Desea eliminar la marca?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
                function () {
                    jQuery.ajax({
                        url: '@Url.Action("EliminarMarca", "Mantenimiento")',
                        type: "POST",
                        data: JSON.stringify({ id: data.IdMarca }),
                        dataType: "json",

                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            if (data.resultado == true) {
                                tablaData.row(marcaSeleccionada).remove().draw();
                            }
                            else {
                                swal("No se pudo eliminar", data.mensaje, "error");
                            }
                        }
                    })
                }
            );

         });



    </script>


}